// 
// AcceptCashDonation.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "Person.h"
#import "Donation.h"
#import "PeopleController.h"

@interface AcceptCashDonation : BasicWindowController {

  Person *person;
  Donation *donation;
  double donationAmount;
  PeopleController *peopleController;
  IBOutlet NSTextField *nameTextField;
  IBOutlet NSTextField *companyTextField;
  IBOutlet NSTextField *addressTextField;
  IBOutlet NSTextField *cityTextField;
  IBOutlet NSTextField *stateTextField;
  IBOutlet NSTextField *zipTextField;
  IBOutlet NSTextField *phoneTextField;
  IBOutlet NSTextField *cookTextField;
  IBOutlet NSTextField *dateTextField;
  IBOutlet NSTextField *emailTextField;
  IBOutlet NSButton *cancelButton;
  IBOutlet NSStepper *amountStepper;
  IBOutlet NSTextField *amountTextField;
  IBOutlet NSButton *fiveButton;
  IBOutlet NSButton *tenButton;
  IBOutlet NSButton *twentyButton;
  IBOutlet NSButton *fiftyButton;
  IBOutlet NSButton *hundredButton;
  IBOutlet NSButton *printButton;
  IBOutlet NSButton *clearCashButton;
  bool runningFromPayInvoice;
  bool runningFromAppController;
  bool runningFromCashDonationManager;

}


//******************************************************************************
// prototypes
//******************************************************************************
- (Person *)person;
- (void)setPerson:(Person *)arg;
- (Donation *)donation;
- (void)setDonation:(Donation *)arg;
- (PeopleController *)peopleController;
- (void)setPeopleController:(PeopleController *)arg;
- (double)donationAmount;
- (void)setDonationAmount:(double)arg;
- (bool)runningFromPayInvoice;
- (void)setRunningFromPayInvoice:(bool)arg;
- (bool)runningFromAppController;
- (void)setRunningFromAppController:(bool)arg;
- (bool)runningFromCashDonationManager;
- (void)setRunningFromCashDonationManager:(bool)arg;


//******************************************************************************
// button actions
//******************************************************************************
- (IBAction)cancelButtonClicked:(id)sender;
- (IBAction)amountStepperClicked:(id)sender;
- (IBAction)fiveButtonClicked:(id)sender;
- (IBAction)tenButtonClicked:(id)sender;
- (IBAction)twentyButtonClicked:(id)sender;
- (IBAction)fiftyButtonClicked:(id)sender;
- (IBAction)hundredButtonClicked:(id)sender;
- (IBAction)printButtonClicked:(id)sender;
- (IBAction)clearCashButtonClicked:(id)sender;


//******************************************************************************
// handlers
//******************************************************************************



//******************************************************************************
// misc
//******************************************************************************
- (void)enablePrintButtonAppropriately;
- (void)incfAmount:(double)delta;

@end