// 
// Book.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "ObjectWithDate.h"
@interface Book : ObjectWithDate {
double startingBalance;
double actualTotal;
double expectedTotal;
double variance;
double totalChecks;
double totalCards;
double totalCash;
double totalCredits;
NSMutableArray *invoiceUids;
NSMutableArray *checkUids;
NSMutableArray *debitUids;
NSMutableArray *creditUids;
NSString *closerNameOrInitials;
int hundreds;
int fifties;
int twenties;
int tens;
int fives;
int twos;
int ones;
bool isOpen;
double untaxableTotal;
double taxableTotal;
double taxOwed;
int projectsCompletedTotal;
double donationsTotal;
double standTimeTotal;
double freeStandTime;
double soldStandTime;
int volunteerHoursTotal;
int numberOfClients;
NSString *pathToPdfArchive;
NSMutableArray *compUids;
double totalValueOfComps;
}


//******************************************************************************
// prototypes
//******************************************************************************
- (double)startingBalance;
- (void)setStartingBalance:(double)arg;
- (double)actualTotal;
- (void)setActualTotal:(double)arg;
- (double)expectedTotal;
- (void)setExpectedTotal:(double)arg;
- (double)variance;
- (void)setVariance:(double)arg;
- (double)totalChecks;
- (void)setTotalChecks:(double)arg;
- (double)totalCards;
- (void)setTotalCards:(double)arg;
- (double)totalCash;
- (void)setTotalCash:(double)arg;
- (double)totalCredits;
- (void)setTotalCredits:(double)arg;
- (NSMutableArray *)invoiceUids;
- (void)setInvoiceUids:(NSArray *)arg;
- (NSMutableArray *)checkUids;
- (void)setCheckUids:(NSArray *)arg;
- (NSMutableArray *)debitUids;
- (void)setDebitUids:(NSArray *)arg;
- (NSMutableArray *)creditUids;
- (void)setCreditUids:(NSArray *)arg;
- (NSString *)closerNameOrInitials;
- (void)setCloserNameOrInitials:(NSString *)arg;
- (int)hundreds;
- (void)setHundreds:(int)arg;
- (int)fifties;
- (void)setFifties:(int)arg;
- (int)twenties;
- (void)setTwenties:(int)arg;
- (int)tens;
- (void)setTens:(int)arg;
- (int)fives;
- (void)setFives:(int)arg;
- (int)twos;
- (void)setTwos:(int)arg;
- (int)ones;
- (void)setOnes:(int)arg;
- (bool)isOpen;
- (void)setIsOpen:(bool)arg;
- (double)untaxableTotal;
- (void)setUntaxableTotal:(double)arg;
- (double)taxableTotal;
- (void)setTaxableTotal:(double)arg;
- (double)taxOwed;
- (void)setTaxOwed:(double)arg;
- (int)projectsCompletedTotal;
- (void)setProjectsCompletedTotal:(int)arg;
- (double)donationsTotal;
- (void)setDonationsTotal:(double)arg;
- (double)standTimeTotal;
- (void)setStandTimeTotal:(double)arg;
- (int)volunteerHoursTotal;
- (void)setVolunteerHoursTotal:(int)arg;
- (int)numberOfClients;
- (void)setNumberOfClients:(int)arg;
- (NSString *)pathToPdfArchive;
- (void)setPathToPdfArchive:(NSString *)arg;
- (double)freeStandTime;
- (void)setFreeStandTime:(double)arg;
- (double)soldStandTime;
- (void)setSoldStandTime:(double)arg;
- (NSMutableArray *)compUids;
- (void)setCompUids:(NSArray *)arg;
- (double)totalValueOfComps;
- (void)setTotalValueOfComps:(double)arg;



//******************************************************************************
// misc
//******************************************************************************
- (NSString *)bookOpenYesOrNo;

@end