// 
// CashDonationManager.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "ViewCashDonation.h"

@interface CashDonationManager : BasicWindowController {

IBOutlet NSTableView *donationsTableView;
IBOutlet NSArrayController *donationsArrayController;
NSMutableArray *donationsArray;
ViewCashDonation *donationViewer;
IBOutlet NSSearchField *donationsSearchField;
int previousLengthOfDonationsSearchString;
IBOutlet NSButton *closeButton;

}


//******************************************************************************
// prototypes
//******************************************************************************
- (NSMutableArray *)donationsArray;
- (void)setDonationsArray:(NSArray *)arg;
- (void)handleDonationsClicked:(id)sender;
- (ViewCashDonation *)donationViewer;
- (void)setDonationViewer:(ViewCashDonation *)arg;


//******************************************************************************
// button actions
//******************************************************************************
- (IBAction)closeButtonClicked:(id)sender;


//******************************************************************************
// handlers
//******************************************************************************
- (void)handleDonationsChange:(NSNotification *)note;
- (void)handleDonationsSearchFieldChange:(NSNotification *)note;


//******************************************************************************
// misc
//******************************************************************************


@end