// 
// CompManager.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "CompViewer.h"

@interface CompManager : BasicWindowController {

IBOutlet NSTableView *compsTableView;
IBOutlet NSArrayController *compsArrayController;
NSMutableArray *compsArray;
CompViewer *compViewer;
IBOutlet NSSearchField *compsSearchField;
int previousLengthOfCompsSearchString;
IBOutlet NSButton *closeButton;

}


//******************************************************************************
// prototypes
//******************************************************************************
- (NSMutableArray *)compsArray;
- (void)setCompsArray:(NSArray *)arg;
- (void)handleCompsClicked:(id)sender;
- (CompViewer *)compViewer;
- (void)setCompViewer:(CompViewer *)arg;


//******************************************************************************
// button actions
//******************************************************************************
- (IBAction)closeButtonClicked:(id)sender;


//******************************************************************************
// handlers
//******************************************************************************
- (void)handleCompsChange:(NSNotification *)note;
- (void)handleCompsSearchFieldChange:(NSNotification *)note;


//******************************************************************************
// misc
//******************************************************************************


@end