// 
// CompClassDescription.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "OWCClassDescription.h"

@interface CompClassDescription : OWCClassDescription {

}


//******************************************************************************
// prototypes
//******************************************************************************


//******************************************************************************
// misc
//******************************************************************************


@end