// 
// CreateAComp.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "Person.h"
#import "Product.h"
#import "PersonSelector.h"
#import "Comp.h"
#import "PersonSelector.h"

@interface CreateAComp : BasicWindowController {
  
  IBOutlet NSTableView *productsTableView;
  IBOutlet NSArrayController *productsArrayController;
  NSMutableArray *productsArray;
  IBOutlet NSTableView *itemsTableView;
  IBOutlet NSArrayController *itemsArrayController;
  NSMutableArray *itemsArray;
  Product *product;
  PersonSelector *personSelector;
  Person *person;
  IBOutlet NSSearchField *productsSearchField;
  int previousLengthOfProductsSearchString;
  IBOutlet NSTextField *personTextField;
  IBOutlet NSTextField *priceTextField;
  IBOutlet NSStepper *priceStepper;
  IBOutlet NSTextField *quantityTextField;
  IBOutlet NSStepper *quantityStepper;
  IBOutlet NSButton *deleteButton;
  IBOutlet NSTextField *cookTextField;
  IBOutlet NSTextField *reasonTextField;
  IBOutlet NSTextView *noteTextView;
  IBOutlet NSDatePicker *datePicker;
  IBOutlet NSButton *cancelButton;
  IBOutlet NSButton *goBackButton;
  IBOutlet NSButton *compButton;
  IBOutlet NSPanel *authorizationPanel;
  IBOutlet NSButton *saveButton;
  IBOutlet NSButton *saveAndPrintButton;
  Comp *comp;
}


//******************************************************************************
// prototypes
//******************************************************************************
- (NSMutableArray *)productsArray;
- (void)setProductsArray:(NSArray *)arg;
- (void)handleProductsClicked:(id)sender;
- (NSMutableArray *)itemsArray;
- (void)setItemsArray:(NSArray *)arg;
- (void)handleItemsClicked:(id)sender;
- (Product *)product;
- (void)setProduct:(Product *)arg;
- (PersonSelector *)personSelector;
- (void)setPersonSelector:(PersonSelector *)arg;
- (Person *)person;
- (void)setPerson:(Person *)arg;
- (Comp *)comp;
- (void)setComp:(Comp *)arg;



  //******************************************************************************
  // button actions
  //******************************************************************************
- (IBAction)priceStepperClicked:(id)sender;
- (IBAction)quantityStepperClicked:(id)sender;
- (IBAction)deleteButtonClicked:(id)sender;
- (IBAction)datePickerClicked:(id)sender;
- (IBAction)cancelButtonClicked:(id)sender;
- (IBAction)goBackButtonClicked:(id)sender;
- (IBAction)compButtonClicked:(id)sender;
- (IBAction)saveButtonClicked:(id)sender;
- (IBAction)saveAndPrintButtonClicked:(id)sender;



  //******************************************************************************
  // handlers
  //******************************************************************************
- (void)handleProductsChange:(NSNotification *)note;
- (void)handleProductsSearchFieldChange:(NSNotification *)note;


  //******************************************************************************
  // misc
  //******************************************************************************
- (void)showPersonSelector;
- (void)enableCompButtonAppropriately;
- (void)enableDoneButtonAppropriately;
- (void)insertObject:(Product *)p inItemsArrayAtIndex:(int)index;
- (void)removeObjectFromItemsArrayAtIndex:(int)index;
- (void)handleItemsSelectionChange:(NSNotification *)note;
- (NSArray *)addableProducts;
- (void)adjustProductPricing;
- (void)createCompAndPrint:(bool)print;



@end