// 
// CreateAComp.m
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import "CreateAComp.h"
#import "Books.h"
#import "Book.h"
#import "Comp.h"
#import "Comps.h"
#import "Products.h"
#import "People.h"
#import "CompArchiver.h"

@implementation CreateAComp

- (id) init {
  self = [super init];
  if (self != nil) {
    [self setRunningModal:NO];
    self = [super initWithWindowNibName:@"CompAProduct"];
    previousLengthOfProductsSearchString = 0;
  }
  return self;
}

//******************************************************************************
// dealloc
//******************************************************************************

- (void) dealloc {
  [productsArray release];
  [itemsArray release];
  [product release];
  [personSelector release];
  [person release];
  [comp release];
  [super dealloc];
}

//******************************************************************************
// windowing
//******************************************************************************

- (void)windowDidLoad {
  [super windowDidLoad];
  [self setupButtons];
  [self setupTextFields];
  [self setupTables];
  [self setupStateVariables];
}

//******************************************************************************

- (void)setupForModal {
  [super setupForModal];
  [self setupButtons];
  [self setupTextFields];
  [self setupTables];
  [self setupStateVariables];
}

//******************************************************************************

- (void)setupForNonModal {
  [super setupForNonModal];
  [self setupButtons];
  [self setupTextFields];
  [self setupTables];
  [self setupStateVariables];
}

//******************************************************************************

- (void)runModalWithParent:(NSWindow *) parent {
  [super runModalWithParent:parent];
}


//******************************************************************************
// setup
//******************************************************************************

- (void)setupButtons {
  [compButton setEnabled:NO];
  [saveButton setEnabled:NO];
  [saveAndPrintButton setEnabled:NO];
  double price = 1.0;
  [priceTextField setDoubleValue:price];
  [priceStepper setDoubleValue:price];
  int quantity = 1;
  [quantityTextField setIntValue:quantity];
  [quantityStepper setIntValue:quantity];
  [datePicker setDateValue:[NSCalendarDate calendarDate]];
}

//******************************************************************************

- (void)setupTextFields {
  [self clearTextField:personTextField];
  [self clearTextField:cookTextField];
  [self clearTextField:reasonTextField];
  [self clearTextView:noteTextView];
  
}

//******************************************************************************

- (void)setupTables {
  [self setProductsArray:[self addableProducts]];
  [productsTableView setTarget:self];
  [productsTableView setDoubleAction:@selector(handleProductsClicked:)];
  
  NSArray *tmp = [[NSArray alloc] init];
  [self setItemsArray:tmp];
  [tmp release];
	[itemsTableView setTarget:self];
  [itemsTableView setDoubleAction:@selector(handleItemsClicked:)];
  [itemsTableView setAction:@selector(handleItemsClicked:)];
  
}

//******************************************************************************

- (void)setupStateVariables {
  [self setProduct:nil];
  [self setComp:nil];
}


//******************************************************************************
// button actions
//******************************************************************************

- (IBAction)priceStepperClicked:(id)sender {
  //NSLog(@"priceStepper clicked");
  if (product != nil) {
    double newPrice = [priceStepper doubleValue];
    [priceTextField setDoubleValue:newPrice];
    [product setProductPrice:newPrice];
    [self adjustProductPricing];
  }
}

//******************************************************************************

- (IBAction)quantityStepperClicked:(id)sender {
  //NSLog(@"quantityStepper clicked");
  if (product != nil) {
    int newQty = [quantityStepper intValue];
    [quantityTextField setIntValue:newQty];
    [product setProductQuantity:newQty];
    [self adjustProductPricing];
  }
}

//******************************************************************************

- (IBAction)deleteButtonClicked:(id)sender {
  //NSLog(@"deleteButton clicked");
  NSArray *selected = [itemsArrayController selectedObjects];
  if ([selected count] > 0) {
		Product *tmp = (Product*)[selected objectAtIndex:0];
		if (tmp != nil) {
      int index = [itemsArrayController selectionIndex];
      [self removeObjectFromItemsArrayAtIndex:index];
      [itemsTableView reloadData];
      [self handleItemsClicked:self];
		}
	}
}

//******************************************************************************

- (IBAction)datePickerClicked:(id)sender {
  //NSLog(@"datePicker clicked");
  // no op
}

//******************************************************************************

- (IBAction)cancelButtonClicked:(id)sender {
  //NSLog(@"cancelButton clicked");
  if (runningModal) {
    [self stopModalAndCloseWindow];
  } else {
    [[self window] close];
  }
}

//******************************************************************************

- (IBAction)compButtonClicked:(id)sender {
  //NSLog(@"compButton clicked");
  [NSApp beginSheet:authorizationPanel
     modalForWindow:[self window]
      modalDelegate:nil
     didEndSelector:nil
        contextInfo:nil];
  
  [NSApp runModalForWindow:authorizationPanel];
  
  [NSApp endSheet:authorizationPanel];
  [authorizationPanel orderOut:self];
  
  // wait for return
  if (comp == nil) {
    // do nothing
  } else {
    [cancelButton performClick:self];
  }
}

//******************************************************************************

- (IBAction)goBackButtonClicked:(id)sender {
  // just to be sure
  [self setComp:nil];
  [NSApp stopModal];
}

//******************************************************************************


- (IBAction)saveButtonClicked:(id)sender {
  //NSLog(@"saveButton clicked");
  [self createCompAndPrint:NO];
  
}

//******************************************************************************

- (IBAction)saveAndPrintButtonClicked:(id)sender {
  //NSLog(@"saveAndPrintButton clicked");
  [self createCompAndPrint:YES];
}

//******************************************************************************

- (void)createCompAndPrint:(bool)print {
  
  [self showProgressPanel:@"Saving..."];
  
  Comp *new = [[Comp alloc] init];
  [new setCommentAuthorName:[self lowercaseAndLatexSafeStringFromTextField:cookTextField]];
  [new setCommentSubject:[self lowercaseAndLatexSafeStringFromTextField:reasonTextField]];
  [new setCommentText:[self lowercaseAndLatexSafeStringFromTextView:noteTextView]];
  [new setDate:[self calendarDateFromDatePicker:datePicker]];
  [new setItems:itemsArray];
  
  // forward
  [new setPersonUid:[person uid]];
  Book *cb = [[Books sharedInstance] currentBook];
  [new setBookUid:[cb uid]];
  
  // backward
  [[cb compUids] addObject:[new uid]];
  [[person compUids] addObject:[new uid]];
  
  [[People sharedInstance] saveToDisk];
  [[Books sharedInstance] saveToDisk];
  [[Comps sharedInstance] setObject:new forUid:[new uid]];
  
  [[CompArchiver sharedInstance] archiveComp:new andPrint:print];
  
  // decf the products
  unsigned int i, count = [itemsArray count];
  for (i = 0; i < count; i++) {
    Product *p = (Product *)[itemsArray objectAtIndex:i];
    Product *root = [[Products sharedInstance] objectForUid:[p uid]];
    int delta = [p productQuantity];
    int original = [root productQuantity];
    [root setProductQuantity:(original - delta)];    
  }
  [[Products sharedInstance] saveToDisk];  

  [self setComp:new];
  [new release];
  [NSApp stopModal];
  [self closeProgressPanel];
}



//******************************************************************************
// misc
//******************************************************************************

- (void)showPersonSelector {
  if (personSelector == nil) {
    PersonSelector *ps = [[PersonSelector alloc] init];
    [self setPersonSelector:ps];
    [ps release];
  }
  [personSelector setupForModal];
  [personSelector runModalWithParent:[self window]];
  // wait for return
  Person *selected = [personSelector person];
  if (selected == nil) {
    [cancelButton performClick:self];
  } else {
    [self setPerson:selected];
    [personTextField setStringValue:[person personName]];
  }
}

//******************************************************************************

- (void)enableCompButtonAppropriately {
  if ([[self window] isKeyWindow]) {
    if ([itemsArray count] > 0) {
      [compButton setEnabled:YES];
    } else {
      [compButton setEnabled:NO];
    }
  }
}

//******************************************************************************

- (void)enableDoneButtonAppropriately {
  if (![self textFieldIsEmpty:cookTextField] &&
      ![self textFieldIsEmpty:reasonTextField]) {
    [saveButton setEnabled:YES];
    [saveAndPrintButton setEnabled:YES];  
  } else {
    [saveButton setEnabled:NO];
    [saveAndPrintButton setEnabled:NO];
  }  
}

//******************************************************************************

- (void)insertObject:(Product *)p inItemsArrayAtIndex:(int)index {
  NSUndoManager *undo = [[self window] undoManager];
  [[undo prepareWithInvocationTarget:self]
    removeObjectFromItemsArrayAtIndex:index];
  if (![undo isUndoing]) {
    [undo setActionName:@"Add Item"];
  }  
  // [self startObservingProduct:p];
  //NSLog(@"itemsArray: %@", itemsArray);
  [itemsArray insertObject:p atIndex:index];
  [self enableCompButtonAppropriately];
}

//******************************************************************************

- (void)removeObjectFromItemsArrayAtIndex:(int)index {
  Product *p = [itemsArray objectAtIndex:index];
  // Add the inverse of this operation to the undo stack
  
  NSUndoManager *undo =  [[self window] undoManager];
  [[undo prepareWithInvocationTarget:self] insertObject:p
                                    inItemsArrayAtIndex:index];
  if (![undo isUndoing]) {
    [undo setActionName:@"Delete Item"];
  }
  //[self stopObservingProduct:p];
  [itemsArray removeObjectAtIndex:index];
  [self enableCompButtonAppropriately];
}

//******************************************************************************

- (void)handleItemsSelectionChange:(NSNotification *)note {
  if ([[self window] isKeyWindow] && [note object] == itemsTableView) {
    [self handleItemsClicked:self];
  }
}

//******************************************************************************

- (NSArray *)addableProducts {
  NSMutableArray *array = [[NSMutableArray alloc] init];
  NSMutableDictionary *all = [[Products sharedInstance] dictionary];
  NSEnumerator *e = [all objectEnumerator];
  Product *val;
  while (val = (Product *)[e nextObject]) {
    NSString *code = [val productCode];
    NSString *cat = [val productCategory];
    if (![code isEqualToString:@"donation"] &&
        ![code isEqualToString:@"stand"]    &&
        ![code isEqualToString:@"project"]  &&
        ![cat isEqualToString:@"Memberships"]) {
      [array addObject:val];
    }
  }
  NSArray *returnVal = [NSArray arrayWithArray:array];
  [array release];
  return returnVal;
}


//******************************************************************************

- (void)adjustProductPricing {
  int qty = [product productQuantity];
  double price = [product productPrice] * qty;
  double percentDiscount = 1.0;
  double discount = price * percentDiscount;
  [product setProductDiscount:discount];
  double total = round(price - discount);
  [product setProductTotal:total];
}

//******************************************************************************
// handlers
//******************************************************************************

- (void) handleProductsSearchFieldChange:(NSNotification *)note {
  if ([[self window] isKeyWindow] && [note object] == productsSearchField) {
    NSString *searchString = [[[note object] stringValue] lowercaseString];
    NSString *codeString, *nameString, *catString, *priceString;
    id object;
    // revert to whole list of objects
    if ( [searchString length] == 0 ) {
      [self setProductsArray:[self addableProducts]];
      previousLengthOfProductsSearchString = 0;
      [productsTableView reloadData];
      return;
    }
    
    // this will hold our filtered list
    NSMutableArray *filteredObjects = [[NSMutableArray alloc] init];
    // if we back up, research the entire list
    if (previousLengthOfProductsSearchString > [searchString length]) {
      [self setProductsArray:[self addableProducts]];
    }
    
    // this needs to be exactly here, otherwise we won't iterate over the correct
    // set of objects
    NSEnumerator *e = [productsArray objectEnumerator];
    while (object = [e nextObject] ) {
      codeString = [[object productCode] lowercaseString];
      NSRange codeRange = [codeString rangeOfString:searchString options:NSLiteralSearch];
      nameString = [[object productName] lowercaseString];
      NSRange nameRange = [nameString rangeOfString:searchString options:NSLiteralSearch];
      catString = [[object productCategory] lowercaseString];
      NSRange catRange = [catString rangeOfString:searchString options:NSLiteralSearch];
      priceString = [NSString stringWithFormat:@"%1.2f", [object productPrice]];
      NSRange priceRange = [priceString rangeOfString:searchString options:NSLiteralSearch];
      
      if (((codeRange.length) > 0) || ((nameRange.length) > 0) || ((catRange.length) > 0) || ((priceRange.length) > 0)) {
        [filteredObjects addObject:object];
      }
    }
    [self setProductsArray:filteredObjects];
    [productsTableView reloadData];
    previousLengthOfProductsSearchString = [searchString length];
    [filteredObjects release];
  }
}


//******************************************************************************

- (void) textDidChange:(NSNotification *)note {
  
  if ([authorizationPanel isKeyWindow]) {
    NSLog(@"isKeyWindow:");
    [self enableDoneButtonAppropriately];
  }
}

//******************************************************************************

- (void)handleProductsChange:(NSNotification *)note {
  NSArray *tmp = [self addableProducts];
  [self setProductsArray:tmp];
  [productsTableView reloadData];
}

//******************************************************************************

- (void)handleProductsClicked:(id)sender {
  //NSLog(@"in handle products clicked");
  NSArray *selected = [productsArrayController selectedObjects];
  if ([selected count] > 0) {
    Product *tmp = (Product *)[selected objectAtIndex:0];
    if (tmp != nil) {
      Product *pcopy = [[Product alloc] init];
      [pcopy setUid:[tmp uid]];
      [pcopy setDisplayName:[tmp displayName]];
      [pcopy setProductName:[tmp productName]];
      [pcopy setProductCategory:[tmp productCategory]];
      [pcopy setProductCode:[tmp productCode]];
      [pcopy setTaxable:[tmp taxable]];
      [pcopy setProductPrice:[tmp productPrice]];
      [pcopy setProductQuantity:1];
      
      [self setProduct:pcopy];
      [pcopy release];
      [self adjustProductPricing];
      
      [itemsArrayController insertObject:pcopy atArrangedObjectIndex:[itemsArray count]];
      [itemsTableView reloadData];
    }
  }
  
}

//******************************************************************************

- (void)handleItemsClicked:(id)sender {
  NSArray *selected = [itemsArrayController selectedObjects];
  if ([selected count] > 0) {
    Product *tmp = (Product *)[selected objectAtIndex:0];
    [self setProduct:tmp];
    if (tmp != nil) {
      double price = [tmp productPrice];
      [priceTextField setDoubleValue:price];
      [priceStepper setDoubleValue:price];
      int quantity = [tmp productQuantity];
      [quantityTextField setIntValue:quantity];
      [quantityStepper setIntValue:quantity];
    }
  } else {
    double price = 1.0;
    [priceTextField setDoubleValue:price];
    [priceStepper setDoubleValue:price];
    int quantity = 1;
    [quantityTextField setIntValue:quantity];
    [quantityStepper setIntValue:quantity];
  }
}


//******************************************************************************
// accessors and setters
//******************************************************************************

- (NSMutableArray *)productsArray {
  return productsArray;
}
- (void) setProductsArray:(NSArray *)arg {
  if (arg != productsArray) {
    [productsArray release];
    productsArray = [arg mutableCopy];
  }
}
- (NSMutableArray *)itemsArray {
  return itemsArray;
}
- (void) setItemsArray:(NSArray *)arg {
  if (arg != itemsArray) {
    [itemsArray release];
    itemsArray = [arg mutableCopy];
  }
}
- (Product *)product {
  return product;
}
- (void) setProduct:(Product *)arg {
  [arg retain];
  [product release];
  product = arg;
}
- (PersonSelector *)personSelector {
  return personSelector;
}
- (void) setPersonSelector:(PersonSelector *)arg {
  [arg retain];
  [personSelector release];
  personSelector = arg;
}
- (Person *)person {
  return person;
}
- (void) setPerson:(Person *)arg {
  [arg retain];
  [person release];
  person = arg;
}
- (Comp *)comp {
  return comp;
}
- (void) setComp:(Comp *)arg {
  [arg retain];
  [comp release];
  comp = arg;
}


//******************************************************************************
// notifications
//******************************************************************************

- (void)setupNotificationObservers {
  NSNotificationCenter *nc;
  nc = [NSNotificationCenter defaultCenter];
  
  [nc addObserver:self
         selector:@selector(handleProductsSearchFieldChange:)
             name:NSControlTextDidChangeNotification
           object:productsSearchField];
  
  [nc addObserver:self
         selector:@selector(textDidChange:)
             name:NSControlTextDidChangeNotification
           object:cookTextField];
  
  [nc addObserver:self
         selector:@selector(textDidChange:)
             name:NSControlTextDidChangeNotification
           object:reasonTextField];
  
  [nc addObserver:self
         selector:@selector(textDidChange:)
             name:NSControlTextDidChangeNotification
           object:noteTextView];
  
  [nc addObserver:self
         selector:@selector(handleProductsChange:)
             name:[[Products sharedInstance] notificationChangeString]
           object:nil];
  
  [nc addObserver:self
         selector:@selector(handleItemsSelectionChange:)
             name:NSTableViewSelectionDidChangeNotification
           object:itemsTableView];
  
}
@end