// 
// DebitOrCredit.m
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import "DebitOrCredit.h"
#import "DOCClassDescription.h"

NSString *TljBkPosDebitString = @"debit";
NSString *TljBkPosCreditString = @"credit";
NSString *TljBkPosDefaultLastFourDigits = @"9999";

@implementation DebitOrCredit


+ (void) initialize {
  if ( self == [DebitOrCredit class] ) {
    id superDescription = [[self superclass] classDescription];
    NSArray *attributeKeys = [superDescription attributeKeys];
    NSDictionary *typeForKey = [superDescription typeForKey];
    NSMutableArray *superAttributes = [NSMutableArray arrayWithArray:attributeKeys];
    NSMutableDictionary *superTypes = [NSMutableDictionary dictionaryWithDictionary:typeForKey];
    DOCClassDescription *cd = [[DOCClassDescription alloc] init];
    [superAttributes addObjectsFromArray:[NSArray arrayWithObjects:@"nameOnDebit",@"debitAmount",@"lastFourDigits",@"expirationDate",@"invoiceUid",@"debitOrCredit",nil]];
    [superTypes setObject:LjStringType forKey:@"nameOnDebit"];
    [superTypes setObject:LjDoubleType forKey:@"debitAmount"];
    [superTypes setObject:LjStringType forKey:@"lastFourDigits"];
    [superTypes setObject:LjCalendarDateType forKey:@"expirationDate"];
    [superTypes setObject:LjStringType forKey:@"invoiceUid"];
    [superTypes setObject:LjStringType forKey:@"debitOrCredit"];
    [cd setAttributeKeys:superAttributes];
    [cd setTypeForKey:superTypes];
    [NSClassDescription registerClassDescription:cd forClass:[self class]];
    [cd release];
  }
}

- (id) init {
  self = [super init];
  if (self != nil) {
    [self setNameOnDebit:@""];
    [self setDebitAmount:0.0];
    [self setLastFourDigits:@""];
    [self setExpirationDate:nil];
    [self setInvoiceUid:@""];
    [self setDebitOrCredit:@""];

  }
  return self;
}


//******************************************************************************
// dealloc
//******************************************************************************
- (void) dealloc {
  [nameOnDebit release];
  [lastFourDigits release];
  [expirationDate release];
  [invoiceUid release];
  [debitOrCredit release];
  [super dealloc];
}


//******************************************************************************
// encode
//******************************************************************************
- (void)encodeWithCoder:(NSCoder *)coder {
  [super encodeWithCoder:coder];
  [coder encodeObject:nameOnDebit forKey:@"nameOnDebit"];
  [coder encodeDouble:debitAmount forKey:@"debitAmount"];
  [coder encodeObject:lastFourDigits forKey:@"lastFourDigits"];
  [coder encodeObject:expirationDate forKey:@"expirationDate"];
  [coder encodeObject:invoiceUid forKey:@"invoiceUid"];
  [coder encodeObject:debitOrCredit forKey:@"debitOrCredit"];
}


//******************************************************************************
// decode
//******************************************************************************
- (id)initWithCoder:(NSCoder *)coder {
  [super initWithCoder:coder];
  [self setNameOnDebit:[coder decodeObjectForKey:@"nameOnDebit"]];
  [self setDebitAmount:[coder decodeDoubleForKey:@"debitAmount"]];
  [self setLastFourDigits:[coder decodeObjectForKey:@"lastFourDigits"]];
  [self setExpirationDate:[coder decodeObjectForKey:@"expirationDate"]];
  [self setInvoiceUid:[coder decodeObjectForKey:@"invoiceUid"]];
  [self setDebitOrCredit:[coder decodeObjectForKey:@"debitOrCredit"]];
 return self;
}


//******************************************************************************
// methods
//******************************************************************************



//******************************************************************************
// accessors and setters
//******************************************************************************
- (NSString *)nameOnDebit {
  return nameOnDebit;
}
- (void) setNameOnDebit:(NSString *)arg {
 arg = [arg copy];
  [nameOnDebit release];
  nameOnDebit = arg;
}
- (double)debitAmount {
  return debitAmount;
}
- (void) setDebitAmount:(double)arg {
 debitAmount = arg;
}
- (NSString *)lastFourDigits {
  return lastFourDigits;
}
- (void) setLastFourDigits:(NSString *)arg {
 arg = [arg copy];
  [lastFourDigits release];
  lastFourDigits = arg;
}
- (NSCalendarDate *)expirationDate {
  return expirationDate;
}
- (void) setExpirationDate:(NSCalendarDate *)arg {
  [arg retain];
  [expirationDate release];
  expirationDate = arg;
}
- (NSString *)invoiceUid {
  return invoiceUid;
}
- (void) setInvoiceUid:(NSString *)arg {
 arg = [arg copy];
  [invoiceUid release];
  invoiceUid = arg;
}
- (NSString *)debitOrCredit {
  return debitOrCredit;
}
- (void) setDebitOrCredit:(NSString *)arg {
 arg = [arg copy];
  [debitOrCredit release];
  debitOrCredit = arg;
}
@end