// 
// DebitOrCredit.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "ObjectWithDate.h"
extern NSString *TljBkPosDebitString;
extern NSString *TljBkPosCreditString;
extern NSString *TljBkPosDefaultLastFourDigits;

@interface DebitOrCredit : ObjectWithDate {
NSString *nameOnDebit;
double debitAmount;
NSString *lastFourDigits;
NSCalendarDate *expirationDate;
NSString *invoiceUid;
NSString *debitOrCredit;
}


//******************************************************************************
// prototypes
//******************************************************************************
- (NSString *)nameOnDebit;
- (void)setNameOnDebit:(NSString *)arg;
- (double)debitAmount;
- (void)setDebitAmount:(double)arg;
- (NSString *)lastFourDigits;
- (void)setLastFourDigits:(NSString *)arg;
- (NSCalendarDate *)expirationDate;
- (void)setExpirationDate:(NSCalendarDate *)arg;
- (NSString *)invoiceUid;
- (void)setInvoiceUid:(NSString *)arg;
- (NSString *)debitOrCredit;
- (void)setDebitOrCredit:(NSString *)arg;

//******************************************************************************
// misc
//******************************************************************************


@end