// 
// Donation.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "ObjectWithDate.h"
#import "ObjectWithDate.h"
#import "Person.h"

@interface Donation : ObjectWithDate {
  bool sentThankYou;
  double donationAmount;
  NSString *donorUid;
  NSString *cookNameOrInitials;
  NSString *pathToPdfArchive;
}


//******************************************************************************
// prototypes
//******************************************************************************
- (bool)sentThankYou;
- (void)setSentThankYou:(bool)arg;
- (double)donationAmount;
- (void)setDonationAmount:(double)arg;
- (NSString *)donorUid;
- (void)setDonorUid:(NSString *)arg;
- (NSString *)cookNameOrInitials;
- (void)setCookNameOrInitials:(NSString *)arg;
- (NSString *)pathToPdfArchive;
- (void)setPathToPdfArchive:(NSString *)arg;


//******************************************************************************
// misc
//******************************************************************************
- (NSString *)sentThankYouYesOrNo;
- (Person *)personForDonation;
- (NSString *)personName;
- (NSString *)companyName;
- (NSString *)personEmail;
- (NSString *)personPhone;
- (NSString *)address;
- (NSString *)city;
- (NSString *)addressState;
- (NSString *)zip;

@end