// 
// InKindDonationManager.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "ViewInKindDonation.h"
#import "AcceptInKindDonation.h"

@interface InKindDonationManager : BasicWindowController {

IBOutlet NSTableView *donationsTableView;
IBOutlet NSArrayController *donationsArrayController;
NSMutableArray *donationsArray;
ViewInKindDonation *donationViewer;
AcceptInKindDonation *inKindDonationCreator;
IBOutlet NSSearchField *donationsSearchField;
int previousLengthOfDonationsSearchString;
IBOutlet NSButton *closeButton;
IBOutlet NSButton *newButton;

}


//******************************************************************************
// prototypes
//******************************************************************************
- (NSMutableArray *)donationsArray;
- (void)setDonationsArray:(NSArray *)arg;
- (void)handleDonationsClicked:(id)sender;
- (ViewInKindDonation *)donationViewer;
- (void)setDonationViewer:(ViewInKindDonation *)arg;
- (AcceptInKindDonation *)inKindDonationCreator;
- (void)setInKindDonationCreator:(AcceptInKindDonation *)arg;


//******************************************************************************
// button actions
//******************************************************************************
- (IBAction)closeButtonClicked:(id)sender;
- (IBAction)newButtonClicked:(id)sender;


//******************************************************************************
// handlers
//******************************************************************************
- (void)handleInKindDonationsChange:(NSNotification *)note;
- (void)handleDonationsSearchFieldChange:(NSNotification *)note;


//******************************************************************************
// misc
//******************************************************************************


@end