// 
// InKindDonation.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "Donation.h"
@interface InKindDonation : Donation {
NSMutableArray *items;
}


//******************************************************************************
// prototypes
//******************************************************************************
- (NSMutableArray *)items;
- (void)setItems:(NSArray *)arg;

//******************************************************************************
// misc
//******************************************************************************


@end