// 
// InvoiceClassDescription.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "OWDClassDescription.h"

@interface InvoiceClassDescription : OWDClassDescription {

}


//******************************************************************************
// prototypes
//******************************************************************************


//******************************************************************************
// misc
//******************************************************************************


@end