// 
// Invoice.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "ObjectWithDate.h"
@class Person;
@class Project;
@class Product;

@interface Invoice : ObjectWithDate {
NSCalendarDate *paidDate;
NSString *personUid;
NSMutableArray *items;
bool invoicePaid;
double invoiceTotal;
double totalAmountReceived;
double amountReceivedCash;
double amountReceivedStoreCredit;
double amountReceivedCreditCard;
double amountReceivedDebitCard;
double amountReceivedCheck;
double amountOfChangeGiven;
int checkNumber;
NSString *nameOnCheck;
NSString *cardBrand;
NSString *cardType;
NSString *lastFourDigits;
NSCalendarDate *expirationDate;
bool nonMemberDiscountGivenP;
double amountOfNonMemberDiscountGiven;
bool memberDiscountGivenP;
double amountOfMemberDiscountGiven;
NSString *pathToPdf;
double hoursOfStandTime;
double totalTaxableAmount;
double totalNonTaxableAmount;
double taxOwed;

}


//******************************************************************************
// prototypes
//******************************************************************************
- (NSCalendarDate *)paidDate;
- (void)setPaidDate:(NSCalendarDate *)arg;
- (NSString *)personUid;
- (void)setPersonUid:(NSString *)arg;
- (NSMutableArray *)items;
- (void)setItems:(NSArray *)arg;
- (bool)invoicePaid;
- (void)setInvoicePaid:(bool)arg;
- (double)invoiceTotal;
- (void)setInvoiceTotal:(double)arg;
- (double)totalAmountReceived;
- (void)setTotalAmountReceived:(double)arg;
- (double)amountReceivedCash;
- (void)setAmountReceivedCash:(double)arg;
- (double)amountReceivedStoreCredit;
- (void)setAmountReceivedStoreCredit:(double)arg;
- (double)amountReceivedCreditCard;
- (void)setAmountReceivedCreditCard:(double)arg;
- (double)amountReceivedDebitCard;
- (void)setAmountReceivedDebitCard:(double)arg;
- (double)amountReceivedCheck;
- (void)setAmountReceivedCheck:(double)arg;
- (double)amountOfChangeGiven;
- (void)setAmountOfChangeGiven:(double)arg;
- (int)checkNumber;
- (void)setCheckNumber:(int)arg;
- (NSString *)nameOnCheck;
- (void)setNameOnCheck:(NSString *)arg;
- (NSString *)cardBrand;
- (void)setCardBrand:(NSString *)arg;
- (NSString *)cardType;
- (void)setCardType:(NSString *)arg;
- (NSString *)lastFourDigits;
- (void)setLastFourDigits:(NSString *)arg;
- (NSCalendarDate *)expirationDate;
- (void)setExpirationDate:(NSCalendarDate *)arg;
- (bool)nonMemberDiscountGivenP;
- (void)setNonMemberDiscountGivenP:(bool)arg;
- (double)amountOfNonMemberDiscountGiven;
- (void)setAmountOfNonMemberDiscountGiven:(double)arg;
- (bool)memberDiscountGivenP;
- (void)setMemberDiscountGivenP:(bool)arg;
- (double)amountOfMemberDiscountGiven;
- (void)setAmountOfMemberDiscountGiven:(double)arg;
- (NSString *)pathToPdf;
- (void)setPathToPdf:(NSString *)arg;
- (double)hoursOfStandTime;
- (void)setHoursOfStandTime:(double)arg;
- (double)totalTaxableAmount;
- (void)setTotalTaxableAmount:(double)arg;
- (double)totalNonTaxableAmount;
- (void)setTotalNonTaxableAmount:(double)arg;
- (double)taxOwed;
- (void)setTaxOwed:(double)arg;

//******************************************************************************
// misc
//******************************************************************************
- (bool)itemsContainsDonationP;
- (double)amountOfDonationInInvoice;
- (bool)invoiceContainsTaxableItemsP;
- (bool)itemsContainsProjectP;
- (Project *)projectForInvoice;
- (Product *)projectProductForInvoice;
- (NSString *)personName;
- (Person *)person;
- (NSString *)paidYesOrNo;
- (double)totalDiscounts;
- (NSString *)searchDescription;

@end