// 
// PayInvoiceController.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "Invoice.h"
#import "Person.h"
#import "AcceptCashDonation.h"
#import "Book.h"


@interface PayInvoiceController : BasicWindowController {

  Person *person;
  Invoice *invoice;
  AcceptCashDonation *acceptCashDonation;
  IBOutlet NSTextField *personInformationTextField;
  IBOutlet NSTextField *cashTextField;
  IBOutlet NSStepper *cashStepper;
  IBOutlet NSButton *fiveButton;
  IBOutlet NSButton *tenButton;
  IBOutlet NSButton *twentyButton;
  IBOutlet NSButton *fiftyButton;
  IBOutlet NSButton *hundredButton;
  IBOutlet NSButton *clearCashButton;
  IBOutlet NSTextField *checkTextField;
  IBOutlet NSStepper *checkStepper;
  IBOutlet NSButton *checkTotalButton;
  IBOutlet NSButton *checkRemainingButton;
  IBOutlet NSButton *checkClearButton;
  IBOutlet NSTextField *checkNumberTextField;
  IBOutlet NSTextField *creditTextField;
  IBOutlet NSStepper *creditStepper;
  IBOutlet NSButton *creditTotalButton;
  IBOutlet NSButton *creditRemainingButton;
  IBOutlet NSButton *creditClearButton;
  IBOutlet NSTextField *creditAvailableTextField;
  IBOutlet NSTextField *cardTextField;
  IBOutlet NSStepper *cardStepper;
  IBOutlet NSButton *cardTotalButton;
  IBOutlet NSButton *cardRemainingButton;
  IBOutlet NSButton *cardClearButton;
  IBOutlet NSComboBox *cardBrandComboBox;
  IBOutlet NSTextField *cardMessageTextField;
  IBOutlet NSComboBox *debitOrCreditComboBox;
  IBOutlet NSDatePicker *expirationDatePicker;
  IBOutlet NSTextField *lastFourDigitsTextField;
  IBOutlet NSTextField *invoiceTextField;
  IBOutlet NSTextField *changeTextField;
  IBOutlet NSTextField *receivedTextField;
  IBOutlet NSButton *clearFormButton;
  IBOutlet NSButton *saveButton;
  IBOutlet NSButton *saveAndPrintButton;
  IBOutlet NSButton *goBackButton;
  
  
}


//******************************************************************************
// prototypes
//******************************************************************************
- (Person *)person;
- (void)setPerson:(Person *)arg;
- (Invoice *)invoice;
- (void)setInvoice:(Invoice *)arg;
- (AcceptCashDonation *)acceptCashDonation;
- (void)setAcceptCashDonation:(AcceptCashDonation *)arg;

//******************************************************************************
// button actions
//******************************************************************************
- (IBAction)cashStepperClicked:(id)sender;
- (IBAction)fiveButtonClicked:(id)sender;
- (IBAction)tenButtonClicked:(id)sender;
- (IBAction)twentyButtonClicked:(id)sender;
- (IBAction)fiftyButtonClicked:(id)sender;
- (IBAction)hundredButtonClicked:(id)sender;
- (IBAction)clearCashButtonClicked:(id)sender;
- (IBAction)checkStepperClicked:(id)sender;
- (IBAction)checkTotalButtonClicked:(id)sender;
- (IBAction)checkRemainingButtonClicked:(id)sender;
- (IBAction)checkClearButtonClicked:(id)sender;
- (IBAction)creditStepperClicked:(id)sender;
- (IBAction)creditTotalButtonClicked:(id)sender;
- (IBAction)creditRemainingButtonClicked:(id)sender;
- (IBAction)creditClearButtonClicked:(id)sender;
- (IBAction)cardStepperClicked:(id)sender;
- (IBAction)cardTotalButtonClicked:(id)sender;
- (IBAction)cardRemainingButtonClicked:(id)sender;
- (IBAction)cardClearButtonClicked:(id)sender;
- (IBAction)expirationDatePickerClicked:(id)sender;
- (IBAction)clearFormButtonClicked:(id)sender;
- (IBAction)saveButtonClicked:(id)sender;
- (IBAction)saveAndPrintButtonClicked:(id)sender;
- (IBAction)goBackButtonClicked:(id)sender;


//******************************************************************************
// handlers
//******************************************************************************


//******************************************************************************
// misc
//******************************************************************************
- (double)updateTotalReceived;
- (void)clearPayments;
- (double)totalCash;
- (double)totalCheck;
- (double)totalCredit;
- (double)totalCard;
- (double)totalReceived;
- (double)changeDue;
- (Product *)donationInInvoice;
- (Product *)standTimeInInvoice;
- (double)priceOfStandTime;
- (void)closeProject;
- (void)decfProductsInInvoice;
- (void)saveInvoiceAndPrint:(bool)print;
- (bool)personIsQuickSale;
- (void)applyPaymentToInvoice;
- (void)applyCreditsToInvoice;
- (void)applyCardsToInvoice;
- (void)applyCheckToInvoice;
- (void)enableSaveButtonsAppropriately;
- (void)showAcceptCashDonation;
- (double)maxCreditAmountAllowed;
- (bool)acceptingCreditCardsP;
- (double)priceOfStandTime;
- (Book *)currentBook;
- (Product *)productForCode:(NSString *)code;
- (Product *)membershipInInvoice;

@end