// 
// PBNClassDescription.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "OWUClassDescription.h"

@interface PBNClassDescription : OWUClassDescription {

}


//******************************************************************************
// prototypes
//******************************************************************************


//******************************************************************************
// misc
//******************************************************************************


@end