// 
// PersonSelector.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "Person.h"
#import "CreateCustomerController.h"

@interface PersonSelector : BasicWindowController {

  Person *person;
  IBOutlet NSTableView *peopleTableView;
  IBOutlet NSArrayController *peopleArrayController;
  NSMutableArray *peopleArray;
  CreateCustomerController *createCustomerController;
  IBOutlet NSTextField *selectedPersonTextField;
  IBOutlet NSSearchField *peopleSearchField;
  int previousLengthOfPeopleSearchString;
  IBOutlet NSButton *quickSaleButton;
  IBOutlet NSButton *addNewButton;
  IBOutlet NSButton *cancelButton;

}


//******************************************************************************
// prototypes
//******************************************************************************
- (Person *)person;
- (void)setPerson:(Person *)arg;
- (NSMutableArray *)peopleArray;
- (void)setPeopleArray:(NSArray *)arg;
- (void)handlePeopleClicked:(id)sender;
- (void)handlePeopleSingleClicked:(id)sender;
- (CreateCustomerController *)createCustomerController;
- (void)setCreateCustomerController:(CreateCustomerController *)arg;


//******************************************************************************
// button actions
//******************************************************************************
- (IBAction)quickSaleButtonClicked:(id)sender;
- (IBAction)addNewButtonClicked:(id)sender;
- (IBAction)cancelButtonClicked:(id)sender;


//******************************************************************************
// handlers
//******************************************************************************
- (void)handlePeopleChange:(NSNotification *)note;
- (void)handlePeopleSearchFieldChange:(NSNotification *)note;
- (void)handlePeopleTableViewSelectionChange:(NSNotification *)note;


//******************************************************************************
// misc
//******************************************************************************

@end