// 
// PersonEditor.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "Person.h"

@interface PersonEditor : BasicWindowController {

  Person *person;
  IBOutlet NSTextField *nameTextField;
  IBOutlet NSTextField *phoneTextField;
  IBOutlet NSTextField *emailTextField;
  IBOutlet NSTextField *companyTextField;
  IBOutlet NSTextField *addressTextField;
  IBOutlet NSTextField *addressStateTextField;
  IBOutlet NSTextField *cityTextField;
  IBOutlet NSTextField *zipTextField;
  IBOutlet NSComboBox *membershipComboBox;
  IBOutlet NSDatePicker *datePicker;
  IBOutlet NSTextField *balanceTextField;
  IBOutlet NSButton *waiverButton;
  IBOutlet NSButton *saveButton;
  IBOutlet NSButton *cancelButton;
  IBOutlet NSButton *checkButton;
  IBOutlet NSButton *closeButton;
}


//******************************************************************************
// prototypes
//******************************************************************************
- (Person *)person;
- (void)setPerson:(Person *)arg;


//******************************************************************************
// button actions
//******************************************************************************
- (IBAction)datePickerClicked:(id)sender;
- (IBAction)waiverButtonClicked:(id)sender;
- (IBAction)saveButtonClicked:(id)sender;
- (IBAction)cancelButtonClicked:(id)sender;
- (IBAction)checkButtonClicked:(id)sender;
- (IBAction)closeButtonClicked:(id)sender;



//******************************************************************************
// handlers
//******************************************************************************



//******************************************************************************
// misc
//******************************************************************************
- (void)enableSaveButtonAppropriately;
- (void)runBadNameWithName:(NSString *)name andBadPhone:(bool)badPhone andBadEmail:(bool)badEmail;
- (void)runBadPhone;
- (void)runBadEmail;
- (void)runEditPerson;


@end