// 
// PreferenceController.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "MembershipInformation.h"

extern NSString *TljBkPosSalesTaxRate;
extern NSString *TljBkPosStartingBookAmount;
extern NSString *TljBkPosWillAcceptCreditCards;
extern NSString *TljBkPosWillAcceptCreditCardsChanged;
extern NSString *TljBkPosCookMembershipInfo;
extern NSString *TljBkPosDeluxeMembershipInfo;
extern NSString *TljBkPosRegularMembershipInfo;
extern NSString *TljBkPosLifetimeMembershipInfo;
extern NSString *TljBkPosAnonymousClientName;

extern NSString *TljBkPosPathToLatexKey;
extern NSString *TljBkPosStandTimeRateKey;
extern NSString *TljBkPosStandTimeProductCode;
extern NSString *TljBkPosProjectProductCode;
extern NSString *TljBkPosDonationProductCode;


@interface PreferenceController : BasicWindowController {

  double salesTax;
  double startingBookAmount;
  bool willAcceptCreditCards;
  IBOutlet NSTableView *membershipInformationTableView;
  IBOutlet NSArrayController *membershipInformationArrayController;
  NSMutableArray *membershipInformationArray;
  IBOutlet NSTextField *salesTaxTextField;
  IBOutlet NSTextField *startingBalanceTextField;
  IBOutlet NSButton *saveStartingBalanceButton;
  IBOutlet NSButton *saveSalesTaxButton;
  IBOutlet NSButton *willAcceptCreditCardsButton;
  IBOutlet NSButton *saveMembershipInformationButton;
  IBOutlet NSTextField *membershipTypeTextField;
  IBOutlet NSTextField *durationTextField;
  IBOutlet NSTextField *priceTextField;
  IBOutlet NSTextField *newPartsDiscountTextField;
  IBOutlet NSTextField *workshopDiscountTextField;
  IBOutlet NSButton *cancelMembershipEditButton;
  
  IBOutlet NSTextField *pathToLatexTextField;
  IBOutlet NSTextField *standTimeRateTextField;
  IBOutlet NSButton *savePathToLatexButton;
  IBOutlet NSButton *saveStandTimeRateButton;
  
  double standTimeRate;
  NSString *pathToLatex;
  
}


//******************************************************************************
// prototypes
//******************************************************************************
- (double)salesTax;
- (void)setSalesTax:(double)arg;
- (double)startingBookAmount;
- (void)setStartingBookAmount:(double)arg;
- (bool)willAcceptCreditCards;
- (void)setWillAcceptCreditCards:(bool)arg;
- (NSMutableArray *)membershipInformationArray;
- (void)setMembershipInformationArray:(NSArray *)arg;
- (void)handleMembershipInformationClicked:(id)sender;
- (double)standTimeRate;
- (void)setStandTimeRate:(double)arg;
- (NSString *)pathToLatex;
- (void)setPathToLatex:(NSString *)arg;


//******************************************************************************
// button actions
//******************************************************************************
- (IBAction)saveSalesTaxButtonClicked:(id)sender;
- (IBAction)saveStartingBalanceButtonClicked:(id)sender;
- (IBAction)willAcceptCreditCardsButtonClicked:(id)sender;
- (IBAction)saveMembershipInformationButtonClicked:(id)sender;
- (IBAction)cancelMembershipEditButton:(id)sender;
- (IBAction)savePathToLatexButtonClicked:(id)sender;
- (IBAction)saveStandTimeRateButtonClicked:(id)sender;



//******************************************************************************
// handlers
//******************************************************************************

- (void)handleMembershipInformationClicked:(id)sender;

//******************************************************************************
// misc
//******************************************************************************
- (double)loadDefaultSalesTax;
- (double)loadDefaultStartingBookAmount;
- (bool)loadDefaultWillAcceptCreditCard;
- (NSMutableArray *)loadDefaultMembershipInformation;
- (void)startObservingMembershipInformation:(MembershipInformation *)info;
- (void)stopObservingMembershipInformation:(MembershipInformation *)info;
- (void)changeKeyPath:(NSString *)keyPath ofObject:(id)obj toValue:(id)newValue;
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context;
- (bool)loadDefaultWillAcceptCreditCard;
- (NSString *)loadDefaultPathToLatex;
- (double)loadDefaultStandTimeRate;

@end