// 
// ProductSelectorForProject.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "Project.h"
#import "Product.h"
#import "Person.h"

@interface ProductSelectorForProject : BasicWindowController {
  
  IBOutlet NSTableView *productsTableView;
  IBOutlet NSArrayController *productsArrayController;
  NSMutableArray *productsArray;
  IBOutlet NSTableView *itemsTableView;
  IBOutlet NSArrayController *itemsArrayController;
  NSMutableArray *itemsArray;
  Project *project;
  Product *product;
  Person *person;
  IBOutlet NSSearchField *productsSearchField;
  int previousLengthOfProductsSearchString;
  IBOutlet NSTextField *priceTextField;
  IBOutlet NSTextField *quantityTextField;
  IBOutlet NSStepper *priceStepper;
  IBOutlet NSStepper *quantityStepper;
  IBOutlet NSButton *deleteButton;
  IBOutlet NSButton *cancelButton;
  IBOutlet NSButton *doneButton;
  
}


//******************************************************************************
// prototypes
//******************************************************************************
- (NSMutableArray *)productsArray;
- (void)setProductsArray:(NSArray *)arg;
- (void)handleProductsClicked:(id)sender;
- (NSMutableArray *)itemsArray;
- (void)setItemsArray:(NSArray *)arg;
- (void)handleItemsClicked:(id)sender;
- (void) handleItemsTableViewSelectionChange:(NSNotification *)note;
- (Project *)project;
- (void)setProject:(Project *)arg;
- (Product *)product;
- (void)setProduct:(Product *)arg;
- (Person *)person;
- (void)setPerson:(Person *)arg;


  //******************************************************************************
  // button actions
  //******************************************************************************
- (IBAction)priceStepperClicked:(id)sender;
- (IBAction)quantityStepperClicked:(id)sender;
- (IBAction)deleteButtonClicked:(id)sender;
- (IBAction)cancelButtonClicked:(id)sender;
- (IBAction)doneButtonClicked:(id)sender;


  //******************************************************************************
  // handlers
  //******************************************************************************
- (void)handleProductsChange:(NSNotification *)note;
- (void)handleProductsSearchFieldChange:(NSNotification *)note;


  //******************************************************************************
  // misc
  //******************************************************************************
- (void)adjustProductPricing;
- (NSArray *)addableProducts;
- (void)insertObject:(Product *)p inItemsArrayAtIndex:(int)index;
- (void)removeObjectFromItemsArrayAtIndex:(int)index;


@end