// 
// ProjectSelector.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "Project.h"
#import "Person.h"
#import "ProjectInformationController.h"

@interface ProjectSelector : BasicWindowController {

IBOutlet NSTableView *projectsTableView;
IBOutlet NSArrayController *projectsArrayController;
NSMutableArray *projectsArray;
Project *project;
Person *person;
IBOutlet NSSearchField *projectsSearchField;
int previousLengthOfProjectsSearchString;
IBOutlet NSButton *cancelButton;
ProjectInformationController *projectInfoViewer;

}


//******************************************************************************
// prototypes
//******************************************************************************
- (NSMutableArray *)projectsArray;
- (void)setProjectsArray:(NSArray *)arg;
- (void)handleProjectsClicked:(id)sender;
- (Project *)project;
- (void)setProject:(Project *)arg;
- (Person *)person;
- (void)setPerson:(Person *)arg;
- (ProjectInformationController *)projectInfoViewer;
- (void)setProjectInfoViewer:(ProjectInformationController *)arg;

//******************************************************************************
// button actions
//******************************************************************************
- (IBAction)cancelButtonClicked:(id)sender;


//******************************************************************************
// handlers
//******************************************************************************
- (void)handleProjectsChange:(NSNotification *)note;
- (void)handleProjectsSearchFieldChange:(NSNotification *)note;


//******************************************************************************
// misc
//******************************************************************************
- (NSMutableArray *)projectsForContext;


@end