// 
// ShopCredit.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "ObjectWithComment.h"
@interface ShopCredit : ObjectWithComment {
double creditAmount;
double remainingAmount;
double usedAmount;
NSString *ownerUid;
bool hasBeenUsed;
NSMutableArray *invoiceUids;
}


//******************************************************************************
// prototypes
//******************************************************************************
- (double)creditAmount;
- (void)setCreditAmount:(double)arg;
- (double)remainingAmount;
- (void)setRemainingAmount:(double)arg;
- (double)usedAmount;
- (void)setUsedAmount:(double)arg;
- (NSString *)ownerUid;
- (void)setOwnerUid:(NSString *)arg;
- (bool)hasBeenUsed;
- (void)setHasBeenUsed:(bool)arg;
- (NSMutableArray *)invoiceUids;
- (void)setInvoiceUids:(NSArray *)arg;

//******************************************************************************
// misc
//******************************************************************************
- (NSString *)hasBeenUsedYesOrNo;
- (NSString *)personName;

@end