// 
// ViewInvoice.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "Invoice.h"

@interface ViewInvoice : BasicWindowController {

Invoice *invoice;
IBOutlet NSTableView *productsTableView;
IBOutlet NSArrayController *productsArrayController;
NSMutableArray *productsArray;
IBOutlet NSTextField *personNameTextField;
IBOutlet NSTextField *paidDateTextField;
IBOutlet NSForm *paymentSummaryForm;
IBOutlet NSTextField *checkNumberTextField;
IBOutlet NSTextField *cardTypeTextField;
IBOutlet NSTextField *expDateTextField;
IBOutlet NSTextField *lastFourDigitsTextField;
IBOutlet NSButton *debitButton;
IBOutlet NSButton *creditButton;
IBOutlet NSButton *printInvoiceButton;
IBOutlet NSButton *closeButton;

}


//******************************************************************************
// prototypes
//******************************************************************************
- (Invoice *)invoice;
- (void)setInvoice:(Invoice *)arg;
- (NSMutableArray *)productsArray;
- (void)setProductsArray:(NSArray *)arg;


//******************************************************************************
// button actions
//******************************************************************************

- (IBAction)printInvoiceButtonClicked:(id)sender;
- (IBAction)closeButtonClicked:(id)sender;


//******************************************************************************
// handlers
//******************************************************************************



//******************************************************************************
// misc
//******************************************************************************


@end