// 
// ViewCashDonation.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "Donation.h"

@interface ViewCashDonation : BasicWindowController {

Donation *donation;
IBOutlet NSTextField *donorTextField;
IBOutlet NSTextField *companyTextField;
IBOutlet NSTextField *addressTextField;
IBOutlet NSTextField *cityTextField;
IBOutlet NSTextField *phoneTextField;
IBOutlet NSTextField *stateTextField;
IBOutlet NSTextField *zipTextField;
IBOutlet NSTextField *dateTextField;
IBOutlet NSTextField *emailTextField;
IBOutlet NSTextField *cookTextField;
IBOutlet NSTextField *creditTextField;
IBOutlet NSButton *thankYouButton;
IBOutlet NSButton *cancelButton;
IBOutlet NSButton *printFormButton;

}


//******************************************************************************
// prototypes
//******************************************************************************
- (Donation *)donation;
- (void)setDonation:(Donation *)arg;


//******************************************************************************
// button actions
//******************************************************************************
- (IBAction)thankYouButtonClicked:(id)sender;
- (IBAction)cancelButtonClicked:(id)sender;
- (IBAction)printFormButtonClicked:(id)sender;


//******************************************************************************
// handlers
//******************************************************************************



//******************************************************************************
// misc
//******************************************************************************


@end