// 
// ViewInKindDonation.h
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import <Cocoa/Cocoa.h>
#import "BasicWindowController.h"
#import "InKindDonation.h"

@interface ViewInKindDonation : BasicWindowController {

InKindDonation *inKindDonation;
IBOutlet NSTableView *itemsTableView;
IBOutlet NSArrayController *itemsArrayController;
NSMutableArray *itemsArray;
IBOutlet NSTextField *donorTextField;
IBOutlet NSTextField *companyTextField;
IBOutlet NSTextField *addressTextField;
IBOutlet NSTextField *cityTextField;
IBOutlet NSTextField *phoneTextField;
IBOutlet NSTextField *stateTextField;
IBOutlet NSTextField *zipTextField;
IBOutlet NSTextField *dataTextField;
IBOutlet NSTextField *emailTextField;
IBOutlet NSTextField *cookTextField;
IBOutlet NSButton *thankYouButton;
IBOutlet NSButton *cancelButton;
IBOutlet NSButton *printFormButton;

}


//******************************************************************************
// prototypes
//******************************************************************************
- (InKindDonation *)inKindDonation;
- (void)setInKindDonation:(InKindDonation *)arg;
- (NSMutableArray *)itemsArray;
- (void)setItemsArray:(NSArray *)arg;
- (void)handleItemsClicked:(id)sender;


//******************************************************************************
// button actions
//******************************************************************************
- (IBAction)thankYouButtonClicked:(id)sender;
- (IBAction)cancelButtonClicked:(id)sender;
- (IBAction)printFormButtonClicked:(id)sender;


//******************************************************************************
// handlers
//******************************************************************************



//******************************************************************************
// misc
//******************************************************************************


@end