// 
// ViewInKindDonation.m
// Generated by auto-coder 1.0
// copyright 2007 The Little Joy.  All rights reserved
#import "ViewInKindDonation.h"
#import "Person.h"
#import "InKindDonationArchiver.h"
#import "InKindDonations.h"

@implementation ViewInKindDonation

- (id) init {
  self = [super init];
  if (self != nil) {
    [self setRunningModal:NO];
    self = [super initWithWindowNibName:@"ViewInKindDonation"];
  }
  return self;
}

//******************************************************************************
// dealloc
//******************************************************************************

- (void) dealloc {
  [inKindDonation release];
  [itemsArray release];
  [super dealloc];
}

//******************************************************************************
// windowing
//******************************************************************************

- (void)windowDidLoad {
   [super windowDidLoad];
   [self setupButtons];
   [self setupTextFields];
   [self setupTables];
   [self setupStateVariables];
}

//******************************************************************************

- (void)setupForModal {
   [super setupForModal];
   [self setupButtons];
   [self setupTextFields];
   [self setupTables];
   [self setupStateVariables];
}

//******************************************************************************

- (void)setupForNonModal {
   [super setupForNonModal];
   [self setupButtons];
   [self setupTextFields];
   [self setupTables];
   [self setupStateVariables];
}

//******************************************************************************

- (void)runModalWithParent:(NSWindow *) parent {
   [super runModalWithParent:parent];
}


//******************************************************************************
// setup
//******************************************************************************

- (void)setupButtons {
  bool thankYou = [inKindDonation sentThankYou];
  [thankYouButton setState:thankYou];
  
}

//******************************************************************************

- (void)setupTextFields {
  Person *p = [inKindDonation personForDonation];
  [donorTextField setStringValue:[p personName]];
  [companyTextField setStringValue:[p companyName]];
  [addressTextField setStringValue:[p address]];
  [cityTextField setStringValue:[p city]];
  [stateTextField setStringValue:[p addressState]];
  [zipTextField setStringValue:[p zip]];
  [phoneTextField setStringValue:[p phoneNumber]];
  NSCalendarDate *date = [inKindDonation date];
  [dataTextField setStringValue:[date descriptionWithCalendarFormat:@"%m/%d/%Y"]];
  [emailTextField setStringValue:[p emailAddress]];
  [cookTextField setStringValue:[inKindDonation cookNameOrInitials]];
  
}

//******************************************************************************

- (void)setupTables {
  [self setItemsArray:[inKindDonation items]];
  // no target actions
}

//******************************************************************************

- (void)setupStateVariables {
  // nothing
}


//******************************************************************************
// button actions
//******************************************************************************

- (IBAction)thankYouButtonClicked:(id)sender {
    //NSLog(@"thankYouButton clicked");
  if ([thankYouButton state] == 1) {
    [inKindDonation setSentThankYou:YES];
  } else {
    [inKindDonation setSentThankYou:NO];
  }
  [[InKindDonations sharedInstance] saveToDisk];
}

//******************************************************************************

- (IBAction)cancelButtonClicked:(id)sender {
    //NSLog(@"cancelButton clicked");
  if (runningModal) {
    [self stopModalAndCloseWindow];
  } else {
    [[self window] close];
  }
}

//******************************************************************************

- (IBAction)printFormButtonClicked:(id)sender {
  //NSLog(@"printFormButton clicked");
  [self showProgressPanel:@"Printing..."];
	[[InKindDonationArchiver sharedInstance] printInKindDonation:[self inKindDonation]];
	[self closeProgressPanel];
}

//******************************************************************************
// handlers
//******************************************************************************

- (void)handleItemsClicked:(id)sender {
}

//******************************************************************************
// accessors and setters
//******************************************************************************

- (InKindDonation *)inKindDonation {
  return inKindDonation;
}
- (void) setInKindDonation:(InKindDonation *)arg {
  [arg retain];
  [inKindDonation release];
  inKindDonation = arg;
}
- (NSMutableArray *)itemsArray {
  return itemsArray;
}
- (void) setItemsArray:(NSArray *)arg {
  if (arg != itemsArray) {
    [itemsArray release];
    itemsArray = [arg mutableCopy];
  }
}


//******************************************************************************
// notifications
//******************************************************************************

- (void)setupNotificationObservers {
     NSNotificationCenter *nc;
     nc = [NSNotificationCenter defaultCenter];

}
@end